# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec3ae9f93691bc191524028b4ab7cf923ee18fb5e913b850808eaa41ee3289a33e2ad23e9216cce71cc5b12e05f3537e1725870e966763be0852b245972c54ce

test:
  secret_key_base: 648b0808628daf3ea0e48ef394a6a28e13a4096b6d3bb2c51cb72056020f2501a7ab88fdfaaa5bef44598dc631418139f1009adba1f09b6f18ff6ca46ecd4ebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
